# Generated by Django 5.0.6 on 2024-05-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_url_clicks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='url',
            name='clicks',
        ),
    ]
