# Generated by Django 5.0.6 on 2024-05-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_url_clicks_alter_url_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='clicks_per_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='url',
            name='clicks_per_month',
            field=models.IntegerField(default=0),
        ),
    ]
